### PR TITLE
Circular Maze

### PR DESCRIPTION
**Pull request by kkaushikvarma**
All the problems that I've brought up in the issue post have been solved. Both the generator and the visualizer work perfectly. What's pending is the implementation of the solving algorithm and visualizing the process (both of generation and solution)

Below are the generated mazes:

3 Layers:
3x3

5 Layers:
5x5

7 Layers:
7x7

9 Layers:
9x9

11 Layers:
11x11

13 Layers:
13x13

### CODE REVIEW

**Comment by jostbr** [comment]
Awesome stuff! Great work. This is a really cool addition to the code, Merged it now.

**Comment by ThomasThelen** [comment]
That's awesome the solver stuff worked out!

In `maze.py`, the `Circle` class inherits from `Maze`, but is setting redundant information in the constructor. For example, 
`self.num_rows = num_rows` is already set in the `Maze` ctor.
Ideally, we would just call the parent ctor and then add any specialized code to the `Circle` constructor. For example, we would still have to set `self.grid_size` (although if we made a function in `Maze` called `get_size` to match yours, it would be a little more generic). The comments on `Circle` can also be mostly removed because they are defined in the parent class.

Example,
```
class Circle(Maze):
    """ Child class of Maze; Contains functions for randomly generating a circular maze.
    Attributes:
        num_rows (int): The number of inner circles
        num_cols (int): Note that these columns are special because blah blah blah
        """
def __init__(self, num_rows, id=0):
     super().__init__()
     num_cols=...
     self.grid_size = self.get_size()
```


Since it looks like there is quite a bit of code overlap/redundancy (see `generate_grid`, `_pick_random_entry_exit`, etc), it probably makes more sense to have a class structure like 

                        Maze
                      /           \
                    /               \
               Square       Circular
 

Instead of 

       Maze
           |
      Circular



In `Cell.py` we have the same code re-use issue in the ctor and class structure in general. It also makes sense to have create a third base class for `square` and `circular` mazes.


In `circle_viz.py` there are some new imports. Update the `requirements.txt` file to reflect these changes. There is also a bunch of code re-use from `maze_viz`, and I don't like the idea of two classes in the source sharing the same name (you can get conflicts when trying to visualize a square _and_ circular maze in the same source file). As with the others, the class structure needs to get re-factored to accommodate for this change. 

What's the difference between `maze_circle.py` and `maze.py`? It looks like they share functions.

All of the maze stuff is hidden from the user by the manager class (It's the facade design pattern). Update the manager class (or preferably create two new managers, `square`, and `circlue`, inherited from MazeManager) to handle the square mazes. 


You're also missing any unit tests. It might also be worth adding two folders to the `examples` directory, `square` and `circular`, be sure to also have an updated readme file.

I wouldn't merge this into `master` yet

**Comment by kkaushikvarma** [comment]
@ThomasThelen I agree. There are quite a few functions that highly redundant. It does need a lot of structure to it. I was trying to make it fit in without making any changes to the code that already exists.   Should have pushed to `dev` instead. My bad

It would be much better to have `square` and `circle` child classes. The parent class can contain the validate functions and can handle the constructor as both the child classes have functions of the same names. For `_pick_random_entry_exit`, a common function may not be possible because the one for the `square` relies on each of the sides while that for `circle` only uses the last column.

I agree that the visualizer still needs a lot of work done. Once it has all the visualization features that exist, we can just set the circle/square as a user parameter and handle everything from maze manager. It would be great if @jostbr can help with the circle visualizer. I'll work on re-structuring the classes for now and then push to `dev` when its the right time.

**Comment by ThomasThelen** [comment]
@kkaushikvarma Thanks for checking that stuff out-I'm impressed how quickly you whipped up the circle code! We may end up with a bunch of abstract methods in the parent classes, which I think _should_ be fine.

We're trying to move to a system where we push to `dev`, and once we all agree that it's stable, we'll merge it into `master`! I know that jostbr is super busy with his master's thesis (and potentially job apps after) so he may not have much time.

**Pull request merged**
