### PR TITLE
Create an Interface to the Library Components

### PR DESCRIPTION
**Pull request by ThomasThelen**
In this commit I first modularized the various components such as the solver, display stuff, and maze.

Check the example files to see how it works! The readme also shows a bit on how to use it.

Fixes issues 
#17 
#5

### CODE REVIEW

**Comment by jostbr** [comment]
Wow, impressive efforts. This looks great!

**Comment by ThomasThelen** [comment]
I'm still not totally satisfied with the way we trigger animation & image saving. I just stuck a variable holding a filename in the visualizer. If it has been set by the user (not empty) then it goes ahead with saving. There's probably a better way. It might be more appropriate for a user to specify the cell size with a function rather than a function parameter. I set a default value to `1` because I'm assuming the average user won't be changing this. A better way might be initializing the value to `1` in the class constructor, taking it out of the function parameters, and creating a new function that sets it.

There are also some comment fields that were left blank. These were things that I was unsure about.

The current code does not 100% conform to the style guide, but we can keep it up as we go....

We may end up putting solver classes into their own files/directory if we end up with a few more.

**Comment by jostbr** [comment]
I was also not completely satisfied with it, but was the best I could think of at the time; if we think of better possibilities, we can add it in the future.

I agree; the average user won't be needing the cell size variable.

I'm totally fine with splitting the solver classes in separate files if there become a few more.

By the way, seems like you have really cleaned up my not optimally structured code. It makes more sense now. Again, appreciate all the work. One question as I'm not that familiar with GitHub: If I have an update I would like to add, do I simply push it as usual or are there other things I should consider now that both have been wrking on it?

**Comment by ThomasThelen** [comment]
I really just restructured the code into a [facade](https://stackoverflow.com/questions/5242429/what-is-facade-design-pattern)! Notice how the user only has to interact with the manager now, and the manager handles all of the complexities. It's a pretty fun trick/design pattern.

You'll of course want to rebase or git pull and then git merge to update your branch beforehand. It's your project so you can do anything you like! It would be nice if you did pull requests though so that I can see any updated code. That way I'll stay up to date with the source.  I can approve them if you [make me a collaborator.](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/).

Also, it looks like pymaze exists :(
https://pypi.python.org/pypi/pymaze/1.2.3

**Comment by jostbr** [comment]
Neat design trick!

I added you as a collaborator. Yes, if/when I make changes I'll make a pull request from a separate branch (that works right?).

Ahh, bummer. Maybe we should change the repository name later, but I think we can keep it for now.

**Pull request merged**
