### PR TITLE
Misc Fixes

### LINKED ISSUE #3: Create Unit Tests

### LINKED ISSUE #4: Add Support for Code Climate and Travis
It would be nice if we could display the current state of the build/unit tests with [Coveralls](https://github.com/coveralls-clients/coveralls-python)

### LINKED ISSUE #11: Move Source Files Into New Directories

### LINKED ISSUE #12: Move Examples Out of Maze Module

### PR DESCRIPTION
**Pull request by ThomasThelen**

### CODE REVIEW

**Comment by jostbr** [comment]
This looks great. Could I change the name of the repository without messing up anything you've done in the pull request? If yes; do you have any suggestions. I feel like MazeGenerator isn't the best fit for the repo anymore as most of the code now involves solving and animating them. I would like to go in a direction of something like maze-lib, maze-viz, maze-fun. Thoughts?

**Comment by ThomasThelen** [comment]
That sounds fantastic. What about something like `pymaze` - A maze generator, solver, and visualizer for python? It would be great to make it an official package with [PyPi](http://peterdowns.com/posts/first-time-with-pypi.html)

I have a couple more fixes in my working branch that I'm not quite ready to commit-but being a C++ guy I think you'll enjoy it!

**Review by jostbr — APPROVED** [review]
Most of the changes have been reviewed and all seems fine. Good update!

**Comment by jostbr** [comment]
Wait, I tried testing the pull request locally and got several syntax errors due to having to manually merge. Did I push to something to master that you didn't have in your branch causing all the conflict? Sorry if this is a stupid question, I'm just not that familiar with git.

**Pull request closed without merging**
